const countryStateMap = {
  Afghanistan: [
    "Badakhshan",
    "Badghis",
    "Baghlan",
    "Balkh",
    "Bamyan",
    "Daykundi",
    "Farah",
  ],
  Australia: [
    "New South Wales",
    "Victoria",
    "Queensland",
    "Tasmania",
    "South Australia",
    "Western Australia",
  ],
  Brazil: [
    "Acre",
    "Alagoas",
    "Amazonas",
    "Bahia",
    "Ceará",
    "Distrito Federal",
    "Espírito Santo",
    "Goiás",
  ],
  Canada: [
    "Alberta",
    "British Columbia",
    "Manitoba",
    "New Brunswick",
    "Newfoundland and Labrador",
    "Nova Scotia",
    "Ontario",
    "Prince Edward Island",
    "Quebec",
    "Saskatchewan",
  ],
  China: [
    "Anhui",
    "Beijing",
    "Chongqing",
    "Fujian",
    "Gansu",
    "Guangdong",
    "Guangxi",
    "Guizhou",
    "Hainan",
    "Hebei",
    "Henan",
    "Hubei",
    "Hunan",
    "Inner Mongolia",
    "Jiangsu",
    "Jiangxi",
    "Jilin",
    "Liaoning",
    "Ningxia",
    "Qinghai",
    "Shaanxi",
    "Shandong",
    "Shanghai",
    "Shanxi",
    "Sichuan",
    "Tianjin",
    "Tibet",
    "Xinjiang",
    "Yunnan",
    "Zhejiang",
  ],
  France: [
    "Auvergne-Rhône-Alpes",
    "Bourgogne-Franche-Comté",
    "Brittany",
    "Centre-Val de Loire",
    "Corsica",
    "Grand Est",
    "Hauts-de-France",
    "Île-de-France",
    "Normandy",
    "Nouvelle-Aquitaine",
    "Occitanie",
    "Pays de la Loire",
    "Provence-Alpes-Côte d'Azur",
  ],
  Germany: [
    "Baden-Württemberg",
    "Bavaria",
    "Berlin",
    "Brandenburg",
    "Bremen",
    "Hamburg",
    "Hesse",
    "Lower Saxony",
    "Mecklenburg-Vorpommern",
    "North Rhine-Westphalia",
    "Rhineland-Palatinate",
    "Saarland",
    "Saxony",
    "Saxony-Anhalt",
    "Schleswig-Holstein",
    "Thuringia",
  ],
  India: [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
    "Andaman and Nicobar Islands",
    "Chandigarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Lakshadweep",
    "Delhi",
    "Puducherry",
    "Ladakh",
    "Jammu and Kashmir",
  ],
  Italy: [
    "Abruzzo",
    "Basilicata",
    "Calabria",
    "Campania",
    "Emilia-Romagna",
    "Friuli Venezia Giulia",
    "Lazio",
    "Liguria",
    "Lombardy",
    "Marche",
    "Molise",
    "Piedmont",
    "Sardinia",
    "Sicily",
    "Tuscany",
    "Trentino-South Tyrol",
    "Umbria",
    "Veneto",
  ],
  Japan: [
    "Aichi",
    "Akita",
    "Aomori",
    "Chiba",
    "Ehime",
    "Fukui",
    "Fukuoka",
    "Fukushima",
    "Gifu",
    "Gunma",
    "Hiroshima",
    "Hokkaido",
    "Hyogo",
    "Ibaraki",
    "Ishikawa",
    "Iwate",
    "Kagawa",
    "Kagoshima",
    "Kanagawa",
    "Kochi",
    "Kumamoto",
    "Kyoto",
    "Mie",
    "Miyagi",
    "Miyazaki",
    "Nagano",
    "Nagasaki",
    "Nara",
    "Niigata",
    "Oita",
    "Okayama",
    "Okinawa",
    "Osaka",
    "Saga",
    "Saitama",
    "Shiga",
    "Shimane",
    "Shizuoka",
    "Tochigi",
    "Tokushima",
    "Tokyo",
    "Tottori",
    "Toyama",
    "Wakayama",
    "Yamagata",
    "Yamaguchi",
    "Yamanashi",
  ],
  Mexico: [
    "Aguascalientes",
    "Baja California",
    "Baja California Sur",
    "Campeche",
    "Chiapas",
    "Chihuahua",
    "Coahuila",
    "Colima",
    "Durango",
    "Guanajuato",
    "Guerrero",
    "Hidalgo",
    "Jalisco",
    "Mexico City",
    "Mexico State",
    "Michoacán",
    "Morelos",
    "Nayarit",
    "Nuevo León",
    "Oaxaca",
    "Puebla",
    "Querétaro",
    "Quintana Roo",
    "San Luis Potosí",
    "Sinaloa",
    "Sonora",
    "Tabasco",
    "Tamaulipas",
    "Tlaxcala",
    "Veracruz",
    "Yucatán",
    "Zacatecas",
  ],
  Russia: [
    "Adygea",
    "Altai Republic",
    "Amur Oblast",
    "Arkhangelsk Oblast",
    "Astrakhan Oblast",
    "Bashkortostan",
    "Belgorod Oblast",
    "Bryansk Oblast",
    "Buryatia",
    "Chechen Republic",
    "Chelyabinsk Oblast",
    "Chukotka Autonomous Okrug",
    "Chuvashia",
    "Dagestan",
    "Irkutsk Oblast",
    "Ivanovo Oblast",
    "Jewish Autonomous Oblast",
    "Kabardino-Balkaria",
    "Kaliningrad Oblast",
    "Kalmykia",
    "Kaluga Oblast",
    "Kamchatka Krai",
    "Karachay-Cherkessia",
    "Karelia",
    "Kemerovo Oblast",
    "Khabarovsk Krai",
    "Khakassia",
    "Khanty-Mansi Autonomous Okrug",
    "Kirov Oblast",
    "Komi",
    "Kostroma Oblast",
    "Krasnodar Krai",
    "Krasnoyarsk Krai",
    "Kurgan Oblast",
    "Kursk Oblast",
    "Leningrad Oblast",
    "Lipetsk Oblast",
    "Magadan Oblast",
    "Mari El",
    "Mordovia",
    "Moscow",
    "Moscow Oblast",
    "Murmansk Oblast",
    "Nenets Autonomous Okrug",
    "Nizhny Novgorod Oblast",
    "North Ossetia–Alania",
    "Novgorod Oblast",
    "Novosibirsk Oblast",
    "Omsk Oblast",
    "Orel Oblast",
    "Orenburg Oblast",
    "Penza Oblast",
    "Perm Krai",
    "Primorsky Krai",
    "Pskov Oblast",
    "Rostov Oblast",
    "Ryazan Oblast",
    "Saint Petersburg",
    "Sakha (Yakutia) Republic",
    "Sakhalin Oblast",
    "Samara Oblast",
    "Saratov Oblast",
    "Sevastopol",
    "Smolensk Oblast",
    "Stavropol Krai",
    "Sverdlovsk Oblast",
    "Tambov Oblast",
    "Tatarstan",
    "Tomsk Oblast",
    "Tula Oblast",
    "Tuva",
    "Tver Oblast",
    "Tyumen Oblast",
    "Udmurtia",
    "Ulyanovsk Oblast",
    "Vladimir Oblast",
    "Volgograd Oblast",
    "Vologda Oblast",
    "Voronezh Oblast",
    "Yamalo-Nenets Autonomous Okrug",
    "Yaroslavl Oblast",
    "Zabaykalsky Krai",
  ],
  "United Kingdom": ["England", "Scotland", "Wales", "Northern Ireland"],
  "United States": [
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
  ],
};

function populateStates() {
  const countryElement = document.getElementById("country");
  const stateElement = document.getElementById("state");
  const selectedCountry = countryElement.value;

  // Clear the existing state options
  stateElement.innerHTML = '<option value="">Select Your State</option>';

  if (selectedCountry && countryStateMap[selectedCountry]) {
    // Get the states for the selected country
    const states = countryStateMap[selectedCountry];

    // Populate the state dropdown
    states.forEach(function (state) {
      var option = document.createElement("option");
      option.value = state;
      option.text = state;
      stateElement.add(option);
    });
  }
}
